import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google"; // TODO: change to one of these: https://similarfont.io/4-google-fonts-similar-to-proxima-nova
import { NavBarContainer } from "@/containers/NavBarContainer";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <NavBarContainer />
        <main className="main">
          {children}
        </main>
      </body>
    </html>
  );
}
