import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import { NavBarContainer } from "@/ui/containers/NavBarContainer";
import "./globals.css";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable}`}>
        <NavBarContainer />
        <main className="main">
          {children}
        </main>
      </body>
    </html>
  );
}
